//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleta()
        {
            this.DetalleBoleta = new HashSet<DetalleBoleta>();
        }
    
        public int idBoleta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal Total { get; set; }
        public bool Eliminado { get; set; }
        public int UsuarioCreadorId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificadorId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int idSucursal { get; set; }
        public int idTrabajador { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleBoleta> DetalleBoleta { get; set; }
        public virtual Trabajador Trabajador { get; set; }
    }
}
