//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.ProductoInventario = new HashSet<ProductoInventario>();
        }
    
        public int idInventario { get; set; }
        public int StockTotal { get; set; }
        public int UsuarioCreadorId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioModificadorId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int idSucursal { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoInventario> ProductoInventario { get; set; }
    }
}
