//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDEFEntities : DbContext
    {
        public BDEFEntities()
            : base("name=BDEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boleta> Boleta { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<DetalleBoleta> DetalleBoleta { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoInventario> ProductoInventario { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Trabajador> Trabajador { get; set; }
    
        public virtual ObjectResult<ObtenerCategoriasMasVendidos_Result> ObtenerCategoriasMasVendidos(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCategoriasMasVendidos_Result>("ObtenerCategoriasMasVendidos", idSucursalParameter);
        }
    
        public virtual ObjectResult<ObtenerProductosConMenosStock_Result> ObtenerProductosConMenosStock(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerProductosConMenosStock_Result>("ObtenerProductosConMenosStock", idSucursalParameter);
        }
    
        public virtual ObjectResult<ObtenerProductosMasVendidos_Result> ObtenerProductosMasVendidos(Nullable<int> idSucursal)
        {
            var idSucursalParameter = idSucursal.HasValue ?
                new ObjectParameter("idSucursal", idSucursal) :
                new ObjectParameter("idSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerProductosMasVendidos_Result>("ObtenerProductosMasVendidos", idSucursalParameter);
        }
    
        public virtual ObjectResult<ObtenerSucursalesConMasVentas_Result> ObtenerSucursalesConMasVentas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerSucursalesConMasVentas_Result>("ObtenerSucursalesConMasVentas");
        }
    }
}
